### ISSUE TITLE
Address generation

### ISSUE THREAD

**Issue by lalanza808** [emesik/monero-python#8]
Hi Michal, is there plans to handle new wallet generation within this repo similar to [Bigreddmachine's implementation](https://github.com/bigreddmachine/MoneroPy/blob/master/moneropy/account.py), Or do you consider that to be outside of the scope?

**Comment by emesik** [comment]
It's definitely within the scope. Tools for generating offline wallets are super important. Ideally, I'd like to have it:

* able to generate sub-accounts and sub-addresses so that a real wallet generated from the seed would recover funds sent there,
* support different mnemonic languages,
* support seed encryption like here: https://xmr.llcoins.net/ (or other standard if it exists),
* use good randomness source on all systems,
* be named in some meaningful way (`Wallet` and `Account` class names are taken already).

I'm not familiar with algorithms used there and my priorities now are to finish the docs, extend functionality of wallet wrapper (payment proofs, multisig) and investigate the *libwallet* backend.

But perhaps you are interested in coding those offline tools?

**Comment by lalanza808** [comment]
Yeah, I'll take a crack at it. I'll probably just make a few issues and knock it out one piece at a time

**Comment by lalanza808** [comment]
Started this on my fork's branch, `mnemonics`: https://github.com/lalanza808/monero-python/blob/mnemonics/monero/seed.py

**Comment by cryptochangements34** [comment]
#9 is ready to be merged which provides the basic functionality required for this.

**Comment by lalanza808** [comment]
We covered the basics with the recent PR's - closing this issue and making specific issues to address the remainder of functionality.
